default_platform(:ios)

platform :ios do
  desc "Build iOS IPA and upload to Firebase App Distribution"
  lane :firebase_release do
    build_app(
      workspace: "smartservemobile.xcworkspace",
      scheme: "smartservemobile",
      configuration: "Release",
      export_method: "ad-hoc",
      output_directory: "build",
      output_name: "SmartServe.ipa"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      ipa_path: "build/SmartServe.ipa",
      groups: "testers",
      release_notes: "SmartServe iOS Jenkins build ##{ENV['BUILD_NUMBER']}"
    )
  end
end