default_platform(:ios)

platform :ios do
  desc "Build iOS app for simulator"
  lane :build_simulator do
    ios_root = File.expand_path("..", __dir__)
    workspace = File.join(ios_root, "smartservemobile.xcworkspace")
    derived_data_path = File.join(ios_root, "build")

    sh("xcodebuild clean build \
      -workspace \"#{workspace}\" \
      -scheme smartservemobile \
      -configuration Release \
      -sdk iphonesimulator \
      -destination 'platform=iOS Simulator,name=iPhone 17' \
      -derivedDataPath \"#{derived_data_path}\"")
  end
end