default_platform(:android)

platform :android do
  desc "Build Android debug APK"
  lane :build_debug do
    gradle(
      task: "assembleDebug"
    )
  end

  desc "Build Android release AAB"
  lane :build_release do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end
end