default_platform(:android)

platform :android do
  desc "Build Android debug APK"
  lane :build_debug do
    gradle(
      task: "assembleDebug"
    )
  end

  desc "Build Android release AAB"
  lane :build_release do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end

  desc "Build Android release APK"
  lane :build_release_apk do
    # Do not use gradle clean here.
    # It can break React Native CMake/codegen cache.
    sh("rm -rf app/.cxx")
    sh("rm -rf app/build")
    sh("rm -rf build")

    gradle(
      task: "assemble",
      build_type: "Release",
      flags: "--no-daemon -PVERSION_CODE=#{ENV['BUILD_NUMBER'] || 1} -PVERSION_NAME=1.0.#{ENV['BUILD_NUMBER'] || 1}"
    )
  end

   desc "Build release APK and upload to Firebase App Distribution"
   lane :firebase_release do
     build_release_apk

     all_apks = lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS] || []

     apk_path = all_apks.find { |path| path.include?("arm64") }

     if apk_path.nil? || !File.exist?(apk_path)
       apk_path = all_apks.first
     end

     if apk_path.nil? || !File.exist?(apk_path)
       apk_path = Dir[File.expand_path("../app/build/outputs/apk/release/*.apk", __dir__)].first
     end

     UI.user_error!("No release APK found") if apk_path.nil? || !File.exist?(apk_path)

     UI.message("Uploading APK: #{apk_path}")

     release_notes = "SmartServe Android Jenkins build ##{ENV['BUILD_NUMBER']}\nCommit: #{`git log -1 --pretty=%s`.strip}"

     success = false
     last_error = nil

     (1..3).each do |attempt|
       begin
         UI.message("Firebase App Distribution upload attempt #{attempt}/3")
         UI.message("Uploading APK: #{apk_path}")

         firebase_app_distribution(
           app: ENV["FIREBASE_ANDROID_APP_ID"],
           firebase_cli_token: ENV["FIREBASE_TOKEN"],
           android_artifact_type: "APK",
           android_artifact_path: apk_path,
           groups: "testers",
           release_notes: release_notes,
           debug: true
         )

         success = true
         break
       rescue => e
         last_error = e
         UI.important("Firebase upload failed on attempt #{attempt}/3")
         UI.important(e.message)

         if attempt < 3
           UI.message("Retrying Firebase upload in 45 seconds...")
           sleep(45)
         end
       end
     end

     UI.user_error!("Firebase upload failed after 3 attempts: #{last_error}") unless success
   end
end